name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
          retention-days: 90

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run typecheck

  validate-blog:
    if: startsWith(github.head_ref, 'blog/')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run validate-blog
          - workin

  update-blogmeta:
    if: startsWith(github.head_ref, 'blog/')
    needs: [validate-blog]
    permissions:
      pages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: git diff --name-only | xargs npx ts-node --esm ./tools/update-blogmeta.ts
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[Bot] Update Blog Meta"
          git push origin ${{github.head_ref}}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build, lint, typecheck]
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
